### ISSUE TITLE
Suggestion to implement Enhanced Branch Protection Rules

### ISSUE THREAD

**Issue by eijidougal** [magicjedi90/etl_utilities#1]
### Description:
To enhance the stability, security, and collaboration of this repository, I propose implementing the following branch protection rules for the main branch. These rules will help ensure that all changes to the main branch undergo proper review and meet high standards of quality and security.

### Proposed Branch Protection Rules for `main`

1. **Restrict Deletions**:  
   Prevent accidental or unauthorized deletion of the `main` branch.  
   **Benefit**: Protects the branch from being removed, ensuring continuity and stability.

2. **Require a Pull Request Before Merging**:  
   Ensure all changes are submitted via pull requests.  
   **Benefit**: Encourages review and discussion before integrating changes.

   - **At Least 1 Required Approval**:  
     Require at least one approval from reviewers for every pull request.  
     **Benefit**: Ensures all code is reviewed by another team member before merging.

   - **Dismiss Stale Pull Request Approvals**:  
     Automatically dismiss approvals when changes are pushed to a pull request.  
     **Benefit**: Ensures that approvals are only valid for the most recent version of the code.

   - **Require Review from Code Owners**:  
     For files with defined code owners, require approval from the respective owners.  
     **Benefit**: Ensures that domain experts review changes to critical parts of the codebase.

   - **Require Conversation Resolution Before Merging**:  
     Prevent merges if there are unresolved conversations on the pull request.  
     **Benefit**: Ensures that all feedback and discussions are addressed before the code is merged.

   - **Request Pull Request Review from Copilot**:  
     Automatically request reviews from GitHub Copilot (or any designated bot/team) for suggestions or additional validation.  
     **Benefit**: Leverages automation for consistency and quality assurance.

3. **Block Force Pushes**:  
   Prevent force pushes to the `main` branch.  
   **Benefit**: Ensures a clean commit history and prevents overwriting changes accidentally or maliciously.

4. **Require Code Scanning Results with CodeQL**:  
   Mandate that CodeQL scans are completed and pass before merging.  
   **Benefit**: Detects potential vulnerabilities and ensures security compliance.

### How to Implement
1. Navigate to the repository's Settings > Branches > Add Rule.
2. Select the main branch and configure the rules as outlined above.

### Benefits of This Change

- Improves the quality and security of code in the `main` branch.
- Enhances collaboration by enforcing peer review and resolving discussions.
- Provides resilience against accidental or unauthorized modifications.
- Aligns with best practices for modern software development and security.

**Comment by magicjedi90** [comment]
Branch policies updated
